{% set name = "jupyterlab_search_replace" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower|replace("_", "-") }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f139bd7de9aa9b9c67a6fa4e0354ade4d9c07e8458e32f0287661c30db91723f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab >=3,<5
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - jupyter_server >=1.0,<3.0
    - ripgrep

test:
  imports:
    - jupyterlab_search_replace
  requires:
    - jupyterlab =4
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_search_replace.*OK"  # [not win]
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-search-replace.*OK.*(python, jupyterlab.search.replace)"  # [not win]

about:
  home: https://github.com/jupyterlab-contrib/search-replace
  summary: Search and replace across files
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcollonval
